sudo: required
language: go
go:
  - 1.6

env:
  - PLATFORM=android-arm
  - PLATFORM=android-x64
  - PLATFORM=android-x86
  - PLATFORM=darwin-x64
  - PLATFORM=linux-x64
  - PLATFORM=linux-x86
  - PLATFORM=linux-arm
  - PLATFORM=windows-x64
  - PLATFORM=windows-x86

services:
  - docker

before_install:
  - make pull

install:
  - make env

script:
  - make $PLATFORM
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      make push
    fi
